# Generated by Django 4.2.9 on 2025-11-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('donji_elementi', 'Donji elementi'), ('gornji_elementi', 'Gornji elementi'), ('visoki_elementi', 'Visoki elementi'), ('ladice', 'Ladice')], max_length=50)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('Dx', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Dy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Dz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='elements/')),
            ],
            options={
                'verbose_name': 'Element SubType',
                'verbose_name_plural': 'Element SubTypes',
                'unique_together': {('type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('donji_elementi', 'Donji elementi'), ('gornji_elementi', 'Gornji elementi'), ('visoki_elementi', 'Visoki elementi'), ('ladice', 'Ladice')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='offers.offer')),
                ('sub_type', models.ForeignKey(limit_choices_to=models.Q(('type', models.F('element_type'))), on_delete=django.db.models.deletion.PROTECT, to='offers.elementsubtype', verbose_name='Sub Type')),
            ],
            options={
                'ordering': ['element_type', 'sub_type'],
            },
        ),
    ]
