# Generated by Django 4.2.9 on 2025-11-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_elementsubtype_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='sub_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', models.F('type'))), on_delete=django.db.models.deletion.PROTECT, to='offers.elementsubtype', verbose_name='Sub Type'),
        ),
    ]
