# Generated by Django 4.2.9 on 2026-01-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_element_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSubTypeElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255, verbose_name='Element Name')),
                ('element_quantity', models.IntegerField(verbose_name='Element Quantity')),
                ('element_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Element Price')),
                ('element_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Element Discount')),
                ('element_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Element Total')),
                ('Dx', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Dy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('Dz', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('element_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.elementsubtype', verbose_name='Element Sub Type')),
            ],
            options={
                'verbose_name': 'ElementSubTypeElements',
                'verbose_name_plural': 'ElementSubTypeElements',
            },
        ),
    ]
