# Generated by Django 4.2.9 on 2026-02-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_elementsubtypeelements'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Coefficient Group',
                'verbose_name_plural': 'Coefficient Groups',
            },
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='offers.coefficientgroup')),
            ],
            options={
                'verbose_name': 'Coefficient',
                'verbose_name_plural': 'Coefficients',
                'unique_together': {('group', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OfferCoefficientSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.coefficient')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.coefficientgroup')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_selections', to='offers.offer')),
            ],
            options={
                'verbose_name': 'Offer Coefficient Selection',
                'verbose_name_plural': 'Offer Coefficient Selections',
                'unique_together': {('offer', 'group')},
            },
        ),
    ]
