# Generated by Django 4.2.9 on 2026-02-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_coefficientgroup_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='Dx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dx'),
        ),
        migrations.AddField(
            model_name='element',
            name='Dy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dy'),
        ),
        migrations.AddField(
            model_name='element',
            name='Dz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dz'),
        ),
    ]
