# Generated by Django 4.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_element_dx_element_dy_element_dz'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsubtypeelements',
            name='formula_code',
            field=models.CharField(blank=True, help_text='Optional: Custom formula identifier for this element. If blank, uses default formulas.', max_length=100, null=True, verbose_name='Formula Code'),
        ),
    ]



