# Generated by Django 4.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_elementsubtypeelements_formula_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficient',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If checked, this coefficient will be automatically selected for new offers', verbose_name='Default'),
        ),
    ]

