 # Generated by Django 4.2.9 on 2026-02-11 21:23

from django.db import migrations, models
import django.db.models.deletion


def add_element_field_safe(apps, schema_editor):
    """Add element field only if it doesn't exist in database"""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("PRAGMA table_info(offers_elementsubtypeelements)")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'element_id' not in columns:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE offers_elementsubtypeelements
                ADD COLUMN element_id INTEGER REFERENCES offers_element(id) ON DELETE CASCADE
            """)


def reverse_add_element_field(apps, schema_editor):
    """Reverse migration - do nothing (SQLite doesn't support DROP COLUMN easily)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_coefficient_is_default'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operation: only add column if it doesn't exist
            database_operations=[
                migrations.RunPython(
                    add_element_field_safe,
                    reverse_code=reverse_add_element_field,
                ),
            ],
            # State operation: always update Django's state to know about the field
            state_operations=[
                migrations.AddField(
                    model_name='elementsubtypeelements',
                    name='element',
                    field=models.ForeignKey(blank=True, help_text='The Element this calculation belongs to. If null, this is a template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_type_elements', to='offers.element', verbose_name='Element'),
                ),
            ],
        ),
    ]
