# Generated by Django 4.2.9 on 2026-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_elementsubtypeelements_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsubtypeelements',
            name='formula_code',
            field=models.CharField(blank=True, help_text='If set, Dx and Dy will be calculated using this formula when saving the offer. The formula calculates both dimensions together.', max_length=100, null=True, verbose_name='Formula Code'),
        ),
    ]
