# Generated by Django 4.2.9 on 2026-02-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_elementsubtypeelements_formula_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementsubtypeelements',
            name='element_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Element Discount'),
        ),
        migrations.AlterField(
            model_name='elementsubtypeelements',
            name='element_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Element Price'),
        ),
        migrations.AlterField(
            model_name='elementsubtypeelements',
            name='element_quantity',
            field=models.IntegerField(default=1, verbose_name='Element Quantity'),
        ),
        migrations.AlterField(
            model_name='elementsubtypeelements',
            name='element_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type_elements', to='offers.elementsubtype', verbose_name='Element Sub Type'),
        ),
        migrations.AlterField(
            model_name='elementsubtypeelements',
            name='element_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Element Total'),
        ),
        migrations.AlterUniqueTogether(
            name='elementsubtypeelements',
            unique_together={('element_sub_type', 'element_name')},
        ),
        migrations.RemoveField(
            model_name='elementsubtypeelements',
            name='Dx',
        ),
        migrations.RemoveField(
            model_name='elementsubtypeelements',
            name='Dy',
        ),
        migrations.RemoveField(
            model_name='elementsubtypeelements',
            name='Dz',
        ),
        migrations.RemoveField(
            model_name='elementsubtypeelements',
            name='element',
        ),
        migrations.CreateModel(
            name='CalculatedElementSubTypeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dx', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dx')),
                ('Dy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Dy')),
                ('element_name', models.CharField(max_length=255, verbose_name='Element Name')),
                ('element_quantity', models.IntegerField(verbose_name='Element Quantity')),
                ('element_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Element Price')),
                ('element_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Element Discount')),
                ('element_total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Element Total')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculated At')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_sub_type_elements', to='offers.element', verbose_name='Element')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_sub_type_elements', to='offers.offer', verbose_name='Offer')),
                ('sub_type_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_instances', to='offers.elementsubtypeelements', verbose_name='Sub Type Element Template')),
            ],
            options={
                'verbose_name': 'Calculated ElementSubTypeElement',
                'verbose_name_plural': 'Calculated ElementSubTypeElements',
                'ordering': ['element', 'sub_type_element__element_name'],
                'unique_together': {('element', 'sub_type_element')},
            },
        ),
    ]
