# Generated by Django 4.2.9 on 2026-04-04 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_user_coefficient_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('vp_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VP Price')),
                ('mp_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MP Price')),
                ('jm', models.CharField(max_length=5, verbose_name='JM')),
                ('Dx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dx')),
                ('Dy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dy')),
                ('Dz', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dz')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='offers.distributor', verbose_name='Distributor')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='offers.material', verbose_name='Material'),
        ),
    ]
