# Generated by Django 4.2.9 on 2026-09-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_rename_element_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
        migrations.AlterModelOptions(
            name='elementsubtype',
            options={'verbose_name': 'Element SubType', 'verbose_name_plural': 'Element SubTypes'},
        ),
        migrations.AlterModelOptions(
            name='offerelement',
            options={'ordering': ['element_type', 'sub_type'], 'verbose_name': 'Offer Element', 'verbose_name_plural': 'Offer Elements'},
        ),
        migrations.AlterField(
            model_name='calculatedelementsubtypeelement',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_sub_type_elements', to='offers.offerelement', verbose_name='Offer Element'),
        ),
        migrations.AlterField(
            model_name='elementsubtype',
            name='element_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type_elements', to='offers.element', verbose_name='Element'),
        ),
        migrations.AlterField(
            model_name='offerelement',
            name='sub_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', models.F('type'))), on_delete=django.db.models.deletion.PROTECT, related_name='offer_elements', to='offers.element', verbose_name='Sub Type'),
        ),
    ]
