# Generated by Django 4.2.9 on 2026-01-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coefficient_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='coefficient_ceiling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='coefficient_floor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='coefficient_tier',
            field=models.BooleanField(default=False),
        ),
    ]
