# Generated by Django 4.2.9 on 2026-01-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_coefficient_back_profile_coefficient_ceiling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Coefficient Group',
                'verbose_name_plural': 'Coefficient Groups',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coefficient_back',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coefficient_ceiling',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coefficient_floor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coefficient_tier',
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='users.coefficientgroup')),
            ],
            options={
                'verbose_name': 'Coefficient',
                'verbose_name_plural': 'Coefficients',
                'unique_together': {('group', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProfileCoefficientSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coefficient')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.coefficientgroup')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficient_selections', to='users.profile')),
            ],
            options={
                'verbose_name': 'Profile Coefficient Selection',
                'verbose_name_plural': 'Profile Coefficient Selections',
                'unique_together': {('profile', 'group')},
            },
        ),
    ]
