# Generated by Django 4.2.9 on 2026-02-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coefficientgroup_remove_profile_coefficient_back_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilecoefficientselection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='profilecoefficientselection',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='profilecoefficientselection',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profilecoefficientselection',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Coefficient',
        ),
        migrations.DeleteModel(
            name='CoefficientGroup',
        ),
        migrations.DeleteModel(
            name='ProfileCoefficientSelection',
        ),
    ]
